[tool.poetry]
name = "repl_python3_GWCHQ"
version = "0.1.0"
description = ""
authors = ["RohidipRider <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
